### ISSUE TITLE
Orang.DotNet.Cli 0.2.0 is not compatible with netcoreapp3.1

### ISSUE THREAD

**Issue by MazurchakVova** [JosefPihrt/Orang#32]
**Version Used**: 0.2.0

**Steps to Reproduce**:  Edit any "*.csproj"
`<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Orang.DotNet.Cli" Version="0.2.0" />
  </ItemGroup>
</Project>`

**Actual Behavior**:
NU1202	Package Orang.DotNet.Cli 0.2.0 is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1). Package Orang.DotNet.Cli 0.2.0 supports: netcoreapp3.1 (.NETCoreApp,Version=v3.1)

**Expected Behavior**:
Installing NuGet package Orang.DotNet.Cli 0.2.0.
Successfully installed 'Orang.DotNet.Cli 0.2.0' to "*.csproj"

**Comment by josefpihrt** [comment]
Hi,

The problem is that Orang is not standard library that can be referenced. It is .NET Core Global Tool. To install Orang please execute following command:

```
dotnet tool install -g orang.dotnet.cli
```

For more information please see [README](https://github.com/JosefPihrt/Orang/blob/master/README.md).
