### ISSUE TITLE
Feature request: Allow inline evaluator expressions

### ISSUE THREAD

**Issue by IanKemp** [JosefPihrt/Orang#4]
[From the sample:](https://github.com/JosefPihrt/Orang#sample-command)

```csharp
using System.Text.RegularExpressions;

namespace N
{
    public static class C
    {
        public static string M(Match match)
        {
            return char.ToUpper(match.Value[0]) + match.Value.Substring(1);
        }
    }
}
```

The only really relevant part of that class is the logic:

```csharp
return char.ToUpper(match.Value[0]) + match.Value.Substring(1);
```

It would be awesome if we could pass such simple logic on the command-line, instead of having to write and compile a full C# DLL. For example, the sample could look like this while providing the same functionality:

```ps
orang replace ^
 --extension txt ^
 --content "pattern.txt" from-file ^
 --evaluator "char.ToUpper(match.Value[0]) + match.Value.Substring(1)" ^
 --highlight match replacement ^
 --display path=omit summary ^
 --dry-run
```

Internally this would use Roslyn to on-the-fly compile the provided expression and execute it. `match` is the implicit name of the `Match`, and only a subset of namespaces are implicitly included - I'd suggest `System`, `System.Linq`, `System.Text`, and `System.Text.RegularExpressions` but you may feel differently.

You could consider adding support for additional command-line-specified namespaces and/or assembly dependencies, much like LINQpad - but I think the relatively simple FR I've outlined here will cover 99% of use-cases, and if users require anything more complex, they can use the current make-your-own-project approach.

**Comment by josefpihrt** [comment]
Great idea!

There could be also third option: specify path to code file that would contain method with signature `string M(MatchEvaluator)`. This option would be suitable for more complicated cases where you cannot specify simple inline expression but it still would be much easier than provide compiled DLL.

**Comment by JosefPihrt** [comment]
I have following proposal how to change `--evaluator` parameter:

1) Value can be parsed as C# expression
```
--evaluator e[xpression]=EXPRESSION
```

2) Value is a valid path to C# code file.
This code file must contain public method with signature `string M(Match)`
```
--evaluator p[ath]=CODE_FILE_PATH
```

3) Value is path to dll file + full method name (currently supported value for this parameter)
```
--evaluator d[ll]=DLL_METHOD_PATH
```
