### ISSUE TITLE
any plan to publish .net library for same functions?

### ISSUE THREAD

**Issue by LeiYangGH** [JosefPihrt/Orang#43]
currently this project is in form of commandline tool.
i think if this project can be easily integrated to other .net projects as a library, it will be even more useful.

**Comment by josefpihrt** [comment]
Hi,

I have an idea to publish .NET client library. Work in progress is here:

https://github.com/JosefPihrt/Orang/blob/main/src/FileSystem/FileSystem/FileSystemSearch.cs

But there is no exact plan when it's going to be published.
